### PR TITLE
added podspec

### PR DESCRIPTION
**Pull request by itsjustcon**

### CODE REVIEW

**Comment by notjosh** [comment]
Bump. Can we get some eyes on this? Any objection to it?

**Comment by jspahrsummers** [comment]
Thanks for the pull request! :sparkles:

However, most of this project's maintainers don't actively use CocoaPods, and so we're not in a good position to maintain and support a podspec. I'd suggest instead submitting it to [CocoaPods/Specs](https://github.com/CocoaPods/Specs).

**Comment by itsjustcon** [comment]
Thanks @jspahrsummers, will do!

**Comment by itchingpixels** [comment]
@itsjustcon sorry to bug you, but do you still have the intention to submit the podspec you've created to the public Specs repo?
If not, please let me know and I'm happy to do it.

**Comment by stefanomondino** [comment]
Hi guys, do you think it would be possible to lower the minimum ios version requirements from 8.0  down to (at least)7.1? I think 8.0 is just a strict requirement to be compatible with carthage, Mantle library supports iOS 5.0 in podspec.

**Pull request closed without merging**
